openhab:
  image:
    repository: openhab/openhab
    tag: 3.2.0
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      persistentVolumeReclaimPolicy: Retain
  env:
    TZ: "Europe/Rome"
    USER_ID: 1000
    GROUP_ID: 1000
