metallb:
  configInline:
    address-pools:
    - name: k8s-ip-space
      protocol: layer2
      addresses:
      - 10.86.15.215-10.86.15.220
    - name: traefik
      protocol: layer2
      addresses:
      - 10.86.15.211/32
      auto-assign: false
    - name: adguard-home
      protocol: layer2
      addresses:
      - 10.86.15.212/32
      auto-assign: false
    - name: personal-ovpn
      protocol: layer2
      addresses:
      - 10.86.15.213/32
      auto-assign: false

