apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgClC7A/tc8vASXWkzlMhK4LjTHohckx3JavR5LvnDN4PiSnxoOEWVkSyfpkLTh2d+IvuADWBGfLkanCPCKbBVJ/v9HReHp8DOIohi1pw/9NAwwhZPDKruD3nx9jsscWRhBg06Sox8+XkitU5Khh3E0qjqTSUO03kRCftLXROwIM7jvf+mMdajaeZPuK1oT2gEWEp4pmHyfRKYLW7R2IVuH1aQMV58cx6ejHoDbW2eOO0zER117rnEzg3di+XieLphegF18a+teL/W80+/EJhwAYadPq7EP8fI/16Enn5cs1u2d4gjHTPNZ9WCnhTrYRLxqiremjEPkwc8Rxwh76KAH2QKQOY24wTCalF3GV9fFgDhGGAdezOtEy0Ta3htSHBF6Wg3lU1ZppvwZOZkv6/pwyGHKiB0cT0sizS4MX/07QQXWoySDe3iYFAfFPNm6NNEJQ1CKM/F3WzahWXOZXLzsptZ6GVLhfIOlcg9fLRaox4xh4Yxnyt1EoZBNyGIjT5lDe1vm6dpxGsauwKIfkh6eJLkfpKVAccZiiWt4Td76+DF+8uhLuL5kNQmJyquegmhPYZPpFuCjFm2V2nXJLpTBHkg1VbS1RzKqjZlBa+mTaJJtEJ5pEZ4+Mw6UZi8PZ77g9mBQWtT9f7m68JmudwQnrYMoxXzocaEbpaH34yYuKBuU3n6F8T4KhZgAs2g8uM7qtLen8I72SzdTmQ8Pf+tyEjtNM6O8QDQTdgX+l2TIOdMjTYxTa
    email: AgBFKL/CSjy2ETwEE0niz1OFmWdEzuvYv1+aXyWfsbo+hOE4IsaeAXpIcgDlaHAX6n2l0R86WPgZQc9+y2qFk+a+pUx9ly28tk4RoVQrLL1iOT4kTQk6lkQvymz7Mx3rZXrEEY9J5zDR/r8r9Achj5HgbQjwUDGHRB5OvFUiZpjZ9cDMkvig8lcwHDAlqZAkYeKaU4Y70RvSKkIwMwh+hJD31qUCbLAX1TTq/cVJH0VriBNlFXxytjf13CEFWCX+RU3FHhJmF+4SKurVTdNzX4j75coL7DApFDhefJvUKG3JTpob5Kq0wzc7iCnAoD+1KG6fx4IqKyqBlOtfPNISaobEnVg8rET2qeLmlvHV8ui/DUunsP8Je4qLBSXiNf88AmgQ3x9adv6w28LRbF2BwMQmn7t7Rux0uGLhUlZOvN1ljnK6zmpbSo3hxgzOCNxk2yf6lEKCa4YLZU+ExEHI7TCPLB35jVqLS44RiC5gtsmk5B1J7qE0WxHEIpSrEkjhgAKjBGbm8zLYSxc8Bn83txCW15VPwF4aQ6+zV1Mcw8BOK4k4R1sfYgC7BQdTgn5wIB9yToRmDj7KkI/+GfgkOlCAOOwkHsKEGr9DeSVxFjByUpG1AgvYimfsgAKPk4R+Rn3cS1d4zDlY4JuradWKQIkczBpcG3WEuuXIt/rz7KrIQpjf4MMYNhjHfCVHml/Ukwh+dqt3k3cwzDBfITobq/7D7NDKYKuwDLZv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik
    type: Opaque

