apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgArfSt7NTqi0LQUMFUzh0dBICif3JmExyEP6ThRF4+khvUMgD0OIHkO8/0sgFKGILNxVyNgaivR03EaqPOroTMXPWyskeJwKldKD5+llppjd5csj+41k9OpGPE7gwMhda04JYiFgIRTvNcVEW2YcJQqMlObldHboIpvhJKh7NtfBxiSpSFvBnYf8ULg8bbyK18R+YOP4IgSH2UQ2nLlLejPCHOYXB1BVQNMlGCwHNebl9iwaq56gulh4LfrA6fr2S/RBHLQ9OAhqB6BMw9OrQENNTYleQpEYKVwfPB8hH4t8Xt3d35SmL/A613lfncyX/wKyHbrDg5PGHnGQwifQ/9j15aBDvCZ/wEscH8s5ebfAiMzug/lUMyJjTyeGTfgYGuXJHQRzFJZezHd4pB+nbJywb0ivUmbI5/myzy136yjJSqT21qVZUZKGLr+vqwGS/WbZmAPZq7n4ZPPVGn7SJVe1ZpbjG4DnWpWht/m4+E2ey4Gb85nBOTPZAjO+uNCbBfhDU/0CiJaQiQtBksgpLWwTItqo2l9IPyvXN6q1YFoyi1Bl6wlTEjY+66847J5guaDbSglZdOf1VVv5V2bJd8a277rwTk+HHJktHRtWkXFcuGdUuIvw7ATYSgjxFEKciOWEid4PO9mUOmUCJlNq+Kv+MQo3yWz7oOYAmCOkYjByh14m2BnugEHXmj0RiCs8D5/j7nrB2J3tb3pv//p4nMWXVjPDizD/jX6dpc2rRar14GBa5/v
    email: AgA9jPuiSfka8blhVmn0PQNpeL6w1so6L7VcGvVp6t5Fj3aHYC6NtjrMIQ2ly6GupPhdUilRN7VQV8TkTMJc5ag5U5XEz8JMvpxN6mPG91AmJPj3xhCXBYMZHS8LZbgDg7k/5STP7+lgJglp3smnxuiBIRB9QDE7modYztpFTvxXZeOyp5DsrevkV2U9HlyPt4yc4TSR/Ylr7xMTcYvYTl5CV6Ymuu8+AHkh6xWKcNWZCajRXXYqZmXN5UiPueH80j/TzmLzD8PAak+ZvD7Jllgz30Yb8o2zgD0qUQ5XY0tz1457ETw1NQPMYKOBjDdZRhXBB2M1RE2dc720z6X1eyIorunt9cTvzDHKGtdzH5OkQcWXiadsuglV0WIn1rAT3s7pl1yeCa/G8fbhi/NsRmDoXQNkTtY+cY2xKXPUBA2Bn5aSU9OKeM5L8kwkZW9kZTyKwt3CTA4lcGSHTnjPDIB6uw2GXfK7hr/A4gjE7IjMMNxMQMRoTjqX9k37uUEl1KxocLw2DHrJPm7oOU0RJ8IU1F0utLBtoJ8uFJDIfYVQzWVZa0FrdtgCjTW3acuP0wt/OgvyNH82nRvA1t/0G7EH4viWepn4Urp5+Xqqe+/K7UsBHMTW37rqfTwOJRXbTEQFUzPJTtl5W5pBzq+XJ8Bc+SlKv9UIQtrLapPN+10Ikyk1Qr4wGOABqF4L6AdI8wm4KDXvseagoJl437sCTDB1NBzliQ8pU5zr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik
    type: Opaque

