mosquitto: 
  service:
    annotations:
      #metallb.universe.tf/address-pool: mosquitto
    #main:
      #type: LoadBalancer
  #spec:
    # Request this permanent IP address for traefik with MetalLB.
    # Kubernetes Master Node has this ip address mapped in /etc/avahi/hosts
    #loadBalancerIP: 172.24.1.12
  env:
    TZ: "Europe/Rome"

  persistence:
    # -- Configure a persistent volume to place mosquitto data in.
    # When enabled, this enables `persistence` and `persistence_location` in the mosquitto config.
    # @default -- See values.yaml
    data:
      enabled: true
      mountPath: /mosquitto/data
      accessMode: ReadWriteOnce
      size: 1Gi
    # -- Configure a persistent volume to place *.conf mosquitto-config-files in.
    # When enabled, this gets set as `include_dir` in the mosquitto config.
    # @default -- See values.yaml
    configinc:
      enabled: true
      mountPath: /mosquitto/configinc
      accessMode: ReadWriteOnce
      size: 100Mi
