spec:
  project: default
  source:
    repoURL: "https://github.com/lucacalcaterra/k0s-prefmc-test.git"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
