spec:
  project: default
  source:
    repoURL: "https://github.com/lucacalcaterra/k0s-home-argocd.git"
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true