qbittorrent:
  persistence:
    media:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      mountPath: /media
    downloads:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      mountPath: /downloads
    # per comunicare vpn e qbt quando vpn pronta
    config:
      enabled: true
      # type: emptyDir
      # mountPath: /config
      # accessMode: ReadWriteOnce
      # size: 1Gi
      # mountPath: /qBittorrent
    shared:
      enabled: true
      type: emptyDir
      mountPath: /shared
    
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568

    # VPN
    env:
      WAIT_FOR_VPN: "true"

  addons:
    vpn:
      enabled: true
      # You might use `openvpn` or `wireguard`
      type: openvpn
      openvpn:
        # VPN settings stored in secret `vpnConfig`. The secret mus have a key
        # a key called `vpnConfigfile` with the openvpn/wireguard config files in them
        authSecret: qbittorrent-vpn-auth
      configFileSecret: qbittorrent-vpn-config
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      env:
        # Set this environment variable to 'on' to make sure all traffic gets routed through the VPN container.
        # Make sure to check the other environment variables for the OpenVPN image to see how you can exclude certain
        # traffic from these firewall rules.
        FIREWALL: "on"

      scripts:
        up: |-
          #!/bin/bash
          /etc/openvpn/up.sh
          echo "connected" > /shared/vpnstatus

        down: |-
          #!/bin/bash
          /etc/openvpn/down.sh
          echo "disconnected" > /shared/vpnstatus
